# Notes 03 Code

# Remember to put data and R script in same folder. Then go to:
#   Session --> Set Working Directory --> To Source File Location


###############################
### Reading in Data section ###
###############################


## Read in STS Course data
# Code was generated by going to Import Dataset --> From Text (readr)

library(readr)
spring2023 <- read_delim("Notes 03 - STS Course Data.txt", 
                         delim = "\t", escape_double = FALSE, 
                         comment = "#", trim_ws = TRUE)
# View(spring2023)

# I commented out the View() function so I don't get a pop-up window every time
#   that I run this script.


# Check that spring2023 is a data frame. Investigate the structure and get a
#   summary of the variables.

is.data.frame(spring2023)
str(spring2023)
summary(spring2023)


# Read in temperature data
# Code was generated by going to Import Dataset --> From Text (readr)

temps <- read_csv("Notes 03 - Temperature Anomalies.txt")


# Read in bison data - Excel file instead of .txt file
# Code was generated by going to Import Dataset --> From Excel.

library(readxl)
bison <- read_excel("Notes 03 - bison.xlsx")



######################################
### Descriptive Statistics section ###
######################################

# Examples of using quantile() function

x <- seq(1, 89, 6)
quantile(x, c(.25, .5, .75))
quantile(x, seq(0, 1, .1))


# Examples using bridges data

library(readxl)
bridges <- read_excel("Notes 03 - NC Bridges.xls", 
                      col_types = c("text", "numeric", "text", 
                                    "text", "numeric", "numeric", "text", 
                                    "text", "numeric", "numeric", "numeric"), 
                      na = "Not Posted")


# Table for one variable or for two variables

table(bridges$FUNCTIONALLYOBSOLETE)
table(bridges$FUNCTIONALLYOBSOLETE, bridges$STRUCTURALLYDEFICIENT)


# length() function gives us number of columns (not rows) in a data frame
# We can use it on a column to get the number of rows

length(bridges)
length(bridges$COUNTY)



###############################
### Data Management section ###
###############################

# Bring up help for ChickWeight and load into environment

?ChickWeight
data("ChickWeight")


# Two ways to select first 12 rows of data

chick1 <- ChickWeight[1:12, ]
head(ChickWeight, n = 12)


# Base R Option to select all of Chick 2's observations

chick2 <- ChickWeight[ChickWeight$Chick == 2, ]
chick2


# Tidyverse Option to do this for Chick 3 - filter() is in dplyr package

library(dplyr)
chick3 <- filter(ChickWeight, Chick == 3)
chick3



# Piping example

# No piping

library(dplyr)
diet1 <- filter(ChickWeight, Diet == 1)
diet1 <- group_by(diet1, Chick)
diet_summary <- summarize(diet1, MaxWt = max(weight))
diet_summary <- arrange(diet_summary, desc(MaxWt))
head(diet_summary, 3)


# Using the piping operator (%>%)

chick_summary <- ChickWeight %>%
  filter(Diet == 1) %>%
  group_by(Chick) %>%
  summarize(MaxWt = max(weight)) %>%
  arrange(desc(MaxWt)) %>%
  head(3)
chick_summary


# Another non-piping approach (not recommended)

head(arrange(summarize(group_by(filter(ChickWeight, Diet == 1), Chick), 
                       MaxWt = max(weight)), desc(MaxWt)), 3)




###################################
### Practice Question Solutions ###
###################################

# Note: There will be multiple ways to do each of these. I've provided one base
#       R option and one Tidyverse option for each. It's also possible to 
#       combine approaches sometimes.

# First one

# Base R option

SD_bridges <- bridges[bridges$STRUCTURALLYDEFICIENT == "SD", ]
table(SD_bridges$COUNTY)

# Tidyverse option

bridges %>%
  filter(STRUCTURALLYDEFICIENT == "SD") %>%
  group_by(COUNTY) %>%
  summarize(SD_Bridges = n())



# Second one - I have to add the age variable first for this script

# Base R option

bridges$AGE <- 2023 - bridges$YEARBUILT
mean_ages <- aggregate(AGE ~ COUNTY, data = bridges, FUN = "mean")
mean_ages <- mean_ages[order(mean_ages$AGE, decreasing = TRUE), ]
head(mean_ages, 5)

# Tidyverse option

bridges <- mutate(bridges, AGE = 2023 - YEARBUILT)
bridges %>%
  group_by(COUNTY) %>%
  summarize(mean_age = mean(AGE)) %>%
  arrange(desc(mean_age)) %>%
  slice(1:5)



# Third one - I have to read the bison data into R for this script

library(readxl)
bison <- read_excel("Notes 03 - bison.xlsx")

# Base R option

bison$bison_to_elk_ratio <- bison$`Bison northern herd` / bison$`Elk northern herd`
plot(bison$Yr, bison$bison_to_elk_ratio)

# Tidyverse option (uses ggplot2 from Notes 4)

bison <- mutate(bison, bison_to_elk_ratio = 
                  `Bison northern herd` / `Elk northern herd`)
ggplot(bison, aes(x = Yr, y = bison_to_elk_ratio)) +
  geom_point()
